In [371]:
import requests
import json
import xlrd
import time
from tqdm import tqdm

def get_info(ordi,des):
#     https://api.map.baidu.com/routematrix/v2/driving?
# "http://api.map.baidu.com/routematrix/v2/driving?output=json&origins=40.45,116.34|40.54,116.35&destinations=40.34,116.45|40.35,116.46&ak=NlO8OYrXPkh3eE8wNKPNhH9RIZZKOVh9"#
    api="http://api.map.baidu.com/routematrix/v2/driving?origins="+ordi+"&destinations="+des+"&ak=wbhijaDzz4ZENFYg99Xpw6MlcBRkB1KZ"#输入目标点经纬度和百度AK（服务器端）
#     print(api)
    req=requests.get(api)
    content=req.content
    ajson=json.loads(content)
    print(ajson['message'])
    res=ajson['result']
    a_list=[] 
    d_list=[]
    t_list=[]
    for i in range(len(res)):
        dis= res[i]['distance']['value']/1000
        time=res[i]['duration']['value']/60
        a_list.append({'距离':dis,'时间':time})
        d_list.append(dis)
        t_list.append(time)
    return a_list,d_list,t_list
#     route=ajson['result']['routes'][0]
#     dis=route['distance']                                #获取通行距离
#     time=route['duration']                               #获取通行时间
#     for i in range(len(route['steps'])):                 #获取每一个step下的道路名称
#         alist.append(route['steps'][i]['road_name'])
#     return dis,time,alist

In [312]:
import math

In [372]:
# d=[]
# t=[]
# t=np.zeros((50,50))
# d=np.zeros((50,50))
for i in range(37,50):
    print(i)
    ordi=str(df.iloc[i,1])+','+str(df.iloc[i,0])
# ordi='22.59495967,113.9882468'
    des=a[:-1]
# '22.59495967,113.9882468|22.53399709,114.0580848|22.56632264,113.9835116'
# |114.0580848,22.53399709|113.9835116,22.56632264 113.9882468,22.59495967
    res,dis,time=get_info(ordi,des)
    bb=np.array(dis).T
    tt=np.array(time).T
    d[i]=bb
    t[i]=tt


37
成功
38
成功
39
成功
40
成功
41
成功
42
成功
43
成功
44
成功
45
成功
46
成功
47
成功
48
成功
49
成功


array([[0.        , 6.91666667, 8.85      , ..., 2.71666667, 9.05      ,
        4.51666667],
       [6.6       , 0.        , 7.96666667, ..., 4.65      , 8.16666667,
        6.8       ],
       [9.23333333, 7.43333333, 0.        , ..., 7.4       , 0.41666667,
        5.53333333],
       ...,
       [2.63333333, 5.13333333, 7.38333333, ..., 0.        , 7.58333333,
        2.91666667],
       [9.2       , 7.38333333, 0.35      , ..., 7.35      , 0.        ,
        5.48333333],
       [4.65      , 6.35      , 5.31666667, ..., 3.31666667, 5.51666667,
        0.        ]])

In [383]:
res=pd.DataFrame(t)
res.to_excel(r'C:/Users/86136/Desktop/建模课设/time50.xlsx',index=None,header=None)

In [132]:
import numpy as np
np.array(dis).T
# d=np.append(a,b,axis=0) 矩阵竖着拼

array([13.768,  5.86 ,  8.263, 12.939, 14.307, 13.786,  9.931, 22.487,
       10.697,  8.761, 17.265,  7.875, 11.71 , 11.427, 10.074,  2.502,
        3.917,  8.752,  2.937, 12.639, 16.188, 10.31 , 10.658, 15.614,
       13.874, 15.067, 13.83 ,  3.514, 10.263, 10.516, 10.783,  9.519,
       11.14 ,  9.024, 14.579,  8.764, 13.813,  9.783,  3.537, 11.788,
       15.649,  1.212,  6.615, 11.227, 21.691, 13.866,  5.476, 11.421,
        8.579, 13.388])

In [111]:
df=pd.read_excel(r'C:/Users/86136/Desktop/建模课设/loc.xlsx',sheet_name='Sheet2',names=['经度','纬度'])
df.head()

经度         纬度
0  114.058085  22.533997
1  113.983512  22.566323
2  114.033637  22.633818
3  114.001502  22.628200
4  114.054137  22.582549

In [309]:
a=''
for i in range(df.iloc[:50,0].shape[0]):
    a=a+str(df.iloc[i,1])+','+str(df.iloc[i,0])+'|'

'22.533997090004117,114.0580847754372|22.566322637979052,113.98351159939614|22.63381797884571,114.03363739231706|22.628200323317376,114.0015020188572|22.582548902113494,114.05413660325073|22.632174549622622,114.09009600065905|22.59911678818979,114.05607911918803|22.59676587774821,114.07710306593115|22.528212817344173,114.01511693013961|22.561852634649238,114.02443934202792|22.54662073538449,114.09161522234936|22.541801328792694,113.99171051800606|22.578155952397477,114.01550245735028|22.52334099317804,113.9916379668523|22.622770818778452,114.014382471378|22.604211715574916,113.99577132403797|22.592636545502216,113.99749229348411|22.6253238187727,114.0480327550672|22.6046760888756,113.988457794766|22.572823195262956,114.03168286336506|22.531208171836145,114.07617132436766|22.635279158092285,114.05110771582518|22.617308273242287,114.0172918299286|22.536246146328573,114.07354373861652|22.629983152950203,114.09136317655158|22.55457388930031,114.07769028832325|22.622542018711144,114.0061631

In [92]:
a=df.iloc[:,1]
a.tolist()

[22.533997090004117,
 22.566322637979052,
 22.63381797884571,
 22.628200323317376,
 22.582548902113494,
 22.632174549622622,
 22.59911678818979,
 22.59676587774821,
 22.528212817344173,
 22.561852634649238,
 22.54662073538449,
 22.541801328792694,
 22.578155952397477,
 22.52334099317804,
 22.622770818778452,
 22.604211715574916,
 22.592636545502216,
 22.6253238187727,
 22.6046760888756,
 22.572823195262956,
 22.531208171836145,
 22.635279158092285,
 22.617308273242287,
 22.536246146328573,
 22.629983152950203,
 22.55457388930031,
 22.622542018711144,
 22.603369920071522,
 22.560577196042118,
 22.5364156089581,
 22.53674848662479,
 22.54929497737139,
 22.63978189466153,
 22.597179150838144,
 22.576626170580276,
 22.549227697776555,
 22.559240764204503,
 22.57963282860934,
 22.603945868119233,
 22.564528593978704,
 22.522801730676683,
 22.590807671320526,
 22.617351222151743,
 22.529021785917372,
 22.596210884110047,
 22.578914684831005,
 22.576408304916328,
 22.558747826132386,
 22.6307

In [56]:
# api="http://api.map.baidu.com/routematrix/v2/driving?output=json&origins=40.45,116.34|40.54,116.35&destinations=40.34,116.45|40.35,116.46&ak=NlO8OYrXPkh3eE8wNKPNhH9RIZZKOVh9"#输入目标点经纬度和百度AK（服务器端）
api='http://api.map.baidu.com/routematrix/v2/driving?output=json&origins=22.59495967,113.9882468&destinations=22.59495967,113.9882468&ak=NlO8OYrXPkh3eE8wNKPNhH9RIZZKOVh9'
req=requests.get(api)
content=req.content
ajson=json.loads(content)

# 下面量化方差

In [ ]:
#道路中点
def count_val(df,df_fea):
    #算重点
    cc=np.zeros((50,50))
    for i in range(50):
        x1=df.iloc[i,0]
        y1=df.iloc[i,1]
        for j in range(50):
            x2=df.iloc[j,0]
            y2=df.iloc[j,1]
            xc=(x1+x2)/2
            yc=(y1+y2)/2
            cc[i][j]=(xc,yc)

In [167]:
cc=np.zeros((50,50))

In [179]:
ccx=np.zeros((50,50))
ccy=np.zeros((50,50))
for i in range(50):
    x1=df.iloc[i,0]
    y1=df.iloc[i,1]
    for j in range(50):
        x2=df.iloc[j,0]
        y2=df.iloc[j,1]
        xc=(x1+x2)/2
        yc=(y1+y2)/2
#         print(xc,yc)
        ccx[i][j]=xc
        ccy[i][j]=yc

In [186]:
df1=pd.read_excel(r'C:/Users/86136/Desktop/建模课设/积水.xlsx')

In [197]:
ccy

array([[22.53399709, 22.55015986, 22.58390753, ..., 22.54637246,
        22.58237068, 22.5545904 ],
       [22.55015986, 22.56632264, 22.60007031, ..., 22.56253523,
        22.59853345, 22.57075317],
       [22.58390753, 22.60007031, 22.63381798, ..., 22.5962829 ,
        22.63228112, 22.60450085],
       ...,
       [22.54637246, 22.56253523, 22.5962829 , ..., 22.55874783,
        22.59474605, 22.56696577],
       [22.58237068, 22.59853345, 22.63228112, ..., 22.59474605,
        22.63074427, 22.60296399],
       [22.5545904 , 22.57075317, 22.60450085, ..., 22.56696577,
        22.60296399, 22.57518371]])

In [194]:
df1.iloc[1:,1][1]

114.055961

In [230]:
for i in range(8):
    for j in range(8):
        js_x=df1.iloc[i][1]
        js_y=df1.iloc[j][2]#循环每个积水路段
        for a in range(50):
            fea1=[]
            for b in range(50):#循环每个点
                d1=math.sqrt(math.pow(ccx[a][b]-js_x,2)+math.pow(ccy[a][b]-js_y,2))
                fea1.append(d1)
                np.array(fea1)
            

KeyboardInterrupt: 

In [276]:
#地球任意两点的距离
from math import radians, cos, sin, asin, sqrt
def gdis(lng1,lat1,lng2,lat2):#经 为
    #lng1,lat1,lng2,lat2 = (120.12802999999997,30.28708,115.86572000000001,28.7427)
    lng1, lat1, lng2, lat2 = map(radians, [float(lng1), float(lat1), float(lng2), float(lat2)]) # 经纬度转换成弧度
    dlon=lng2-lng1
    dlat=lat2-lat1
    a=sin(dlat/2)**2 + cos(lat1) * cos(lat2) * sin(dlon/2)**2
    distance=2*asin(sqrt(a))*6371*1000 # 地球平均半径，6371km
    distance=round(distance/1000,3)
    return distance

In [400]:
def fea_juzhen(cxx,cyy,df1):
    js_min=np.zeros((50,50))
#     js_min=np.array(js_min)
    for a in range(50):
        js_min_h=[]
        for b in range(50):#循环每个点
            xc=ccx[a][b]
            yc=ccy[a][b]
            ddd=[]
            for i in range(df1.shape[0]):
                js_x=df1.iloc[i][1]
                js_y=df1.iloc[i][2]
                d1=gdis(ccx[a][b],ccy[a][b],js_x,js_y)
    #             math.sqrt(math.pow(ccx[a][b]-js_x,2)+math.pow(ccy[a][b]-js_y,2))
                ddd.append(d1)#每个点对应的八个距离
            js_min_h.append(min(ddd))
            hang=np.array(js_min_h)
        js_min[a]=hang
    return js_min
#         js_min=np.r_[js_min,hang]

In [297]:
def shangquan(cxx,cyy,df1):

    js_min=[]
    js_min=np.array(js_min)
    for a in range(50):
        js_min_h=[]
        for b in range(50):#循环每个点
            xc=ccx[a][b]
            yc=ccy[a][b]
            ddd=[]
            for i in range(df1.shape[0]):
                js_x=df1.iloc[i][1]
                js_y=df1.iloc[i][2]
                d1=gdis(ccx[a][b],ccy[a][b],js_x,js_y)
    #             math.sqrt(math.pow(ccx[a][b]-js_x,2)+math.pow(ccy[a][b]-js_y,2))
                ddd.append(d1)#每个点对应的八个距离
            js_min_h.append(min(ddd))
            hang=np.array(js_min_h)
        js_min=np.append(js_min,hang)
    return js_min

In [298]:
aaabs=shangquan(ccx,ccy,df1)

In [300]:
res=pd.DataFrame(aaabs)
res.to_excel(r'C:/Users/86136/Desktop/建模课设/积水熵权.xlsx')

In [301]:
df2=pd.read_excel(r'C:/Users/86136/Desktop/建模课设/事故.xlsx')
aaab=shangquan(ccx,ccy,df2)

In [305]:
res=pd.DataFrame(aaab)
res.to_excel(r'C:/Users/86136/Desktop/建模课设/事故熵权.xlsx')

In [393]:
df3=pd.read_excel(r'C:/Users/86136/Desktop/建模课设/商场.xlsx',header=None)
aaab=shangquan(ccx,ccy,df3)
res=pd.DataFrame(aaab)
res.to_excel(r'C:/Users/86136/Desktop/建模课设/人流量熵权.xlsx')

In [401]:
fea1=fea_juzhen(ccx,ccy,df1)

In [404]:
fea2=fea_juzhen(ccx,ccy,df2)
fea3=fea_juzhen(ccx,ccy,df3)

In [405]:
f1=pd.DataFrame(fea1)
f2=pd.DataFrame(fea2)
f3=pd.DataFrame(fea3)

In [440]:
jieguo=0.308227898563264*f2+0.387103909087*f1+0.304668192348933*f3

In [419]:
maxx=jieguo.max().max()
mini=jieguo.min().min()
rr=(maxx-mini)/3

In [421]:
rr,rr*2

(2.744909882415712, 5.489819764831424)

In [422]:
mini,maxx

(0.6031526252513192, 8.837882272498454)

In [424]:
jieguo[mini<jieguo<rr]

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [441]:
jieguo[(jieguo>=mini)&(jieguo<rr)]=50

In [443]:
jieguo[(jieguo>=rr)&(jieguo<rr*2)]=100
jieguo[(jieguo>=rr*2)&(jieguo<=maxx)]=150

In [473]:
jieguo[(jieguo==5)]=0.95

In [474]:
jieguo[(jieguo==10)]=0.9
jieguo[(jieguo==15)]=0.85

In [475]:
res=pd.DataFrame(jieguo)
res.to_excel(r'C:/Users/86136/Desktop/建模课设/方差.xlsx',index=None,header=None)

In [451]:
d.max()

27.557

In [454]:
t.describe()

AttributeError: 'numpy.ndarray' object has no attribute 'describe'

319.3

array([ 6.6       ,  0.        ,  7.96666667, 10.88333333,  6.45      ,
       11.41666667,  8.68333333, 11.8       ,  4.68333333,  2.98333333,
        8.28333333,  2.91666667,  4.83333333,  5.13333333,  9.1       ,
        4.96666667,  5.15      ,  8.26666667,  5.58333333,  5.41666667,
        8.15      ,  9.25      ,  9.46666667,  7.51666667, 11.46666667,
        6.93333333, 11.45      ,  5.15      ,  4.23333333,  4.56666667,
        4.73333333,  3.95      ,  9.76666667,  7.5       ,  6.61666667,
        3.43333333,  6.15      ,  3.61666667,  5.16666667,  4.88333333,
        7.71666667,  4.26666667,  6.46666667,  5.01666667, 11.3       ,
        6.7       ,  1.93333333,  4.65      ,  8.16666667,  6.8       ])